# Uncomment this line to define a global platform for your project
platform :ios, "13.0"
use_frameworks!
inhibit_all_warnings!

#source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
end

target 'ApolloTest' do
	shared_pods
end
